/* eslint-disable max-lines */
export const optionsStores = {
  items: [
    {
      id: 'b34579be-3ee7-483e-b30d-243e568085b0',
      name: 'Kennedy - Bogotá',
      address: 'Calle 6 # 72 - 7',
    },
    {
      id: 'b34579be-3ee7-483e-b30d-243e568085b1',
      name: 'Treinta Montevideo MU - Bogotá',
      address: 'Calle 17a # 69B - 74',
    },
  ],
};

export const optionsCategories = {
  items: [
    {
      name: 'Bebidas en Polvo',
      id: 92,
      thumbImgUrl: 'null',
      parentId: 7,
    },
    {
      name: 'Chicles y mentas',
      id: 75,
      thumbImgUrl: 'null',
      parentId: 5,
    },
    {
      name: 'Salud digestiva',
      id: 102,
      thumbImgUrl: 'null',
      parentId: 9,
    },
    {
      name: 'Limpia Vidrios',
      id: 67,
      thumbImgUrl: 'null',
      parentId: 4,
    },
    {
      name: 'Esparcibles',
      id: 39,
      thumbImgUrl: 'null',
      parentId: 2,
    },
    {
      name: 'Vodkas',
      id: 22,
      thumbImgUrl: 'null',
      parentId: 1,
    },
    {
      name: 'Blanqueadores y Limpidos',
      id: 65,
      thumbImgUrl: 'null',
      parentId: 4,
    },
    {
      name: 'Leches',
      id: 81,
      thumbImgUrl: 'null',
      parentId: 5,
    },
    {
      name: 'Panes, Tortillas y Arepas',
      id: 43,
      thumbImgUrl: 'null',
      parentId: 2,
    },
    {
      name: 'Chocolates',
      id: 73,
      thumbImgUrl: 'null',
      parentId: 5,
    },
    {
      name: 'Vitaminas y Suplementos',
      id: 103,
      thumbImgUrl: 'null',
      parentId: 9,
    },
    {
      name: 'Lácteos de Lonchera',
      id: 87,
      thumbImgUrl: 'null',
      parentId: 6,
    },
    {
      name: 'Vinos',
      id: 18,
      thumbImgUrl: 'null',
      parentId: 1,
    },
    {
      name: 'Jabones Líquidos Personal',
      id: 50,
      thumbImgUrl: 'null',
      parentId: 2,
    },
    {
      name: 'Cuidado de la Piel',
      id: 51,
      thumbImgUrl: 'null',
      parentId: 3,
    },
    {
      name: 'Cocteles Listos',
      id: 24,
      thumbImgUrl: 'null',
      parentId: 1,
    },
    {
      name: 'Masticables',
      id: 72,
      thumbImgUrl: 'null',
      parentId: 4,
    },
    {
      name: 'Jugos y Tes',
      id: 90,
      thumbImgUrl: 'null',
      parentId: 6,
    },
    {
      name: 'Desinfectantes',
      id: 62,
      thumbImgUrl: 'null',
      parentId: 4,
    },
    {
      name: 'Cuidado Oral',
      id: 55,
      thumbImgUrl: 'null',
      parentId: 3,
    },
    {
      name: 'Suavizantes y Aromatizantes',
      id: 61,
      thumbImgUrl: 'null',
      parentId: 4,
    },
    {
      name: 'Toallas, Paños y Servilletas',
      id: 63,
      thumbImgUrl: 'null',
      parentId: 4,
    },
    {
      name: 'Jabon Barra Hogar',
      id: 60,
      thumbImgUrl: 'null',
      parentId: 4,
    },
    {
      name: 'Pañales',
      id: 107,
      thumbImgUrl: 'null',
      parentId: 10,
    },
    {
      name: 'Aseo Mascotas',
      id: 105,
      thumbImgUrl: 'null',
      parentId: 9,
    },
    {
      name: 'Alimentos para Bebés',
      id: 111,
      thumbImgUrl: 'null',
      parentId: 11,
    },
    {
      name: 'Bebidas Energéticas',
      id: 93,
      thumbImgUrl: 'null',
      parentId: 7,
    },
    {
      name: 'Lácteos en polvo',
      id: 82,
      thumbImgUrl: 'null',
      parentId: 5,
    },
    {
      name: 'Crema de Leche',
      id: 84,
      thumbImgUrl: 'null',
      parentId: 6,
    },
    {
      name: 'Cuidado del Cabello',
      id: 54,
      thumbImgUrl: 'null',
      parentId: 3,
    },
    {
      name: 'Detergentes Liquidos',
      id: 58,
      thumbImgUrl: 'null',
      parentId: 3,
    },
    {
      name: 'Velas',
      id: 118,
      thumbImgUrl: 'null',
      parentId: 12,
    },
    {
      name: 'Shampoos y Jabones Bebés',
      id: 110,
      thumbImgUrl: 'null',
      parentId: 11,
    },
    {
      name: 'Papel Higienico',
      id: 56,
      thumbImgUrl: 'null',
      parentId: 3,
    },
    {
      name: 'Primeros auxilios',
      id: 100,
      thumbImgUrl: 'null',
      parentId: 8,
    },
    {
      name: 'Leche Condensada',
      id: 85,
      thumbImgUrl: 'null',
      parentId: 6,
    },
    {
      name: 'Sal',
      id: 35,
      thumbImgUrl: 'null',
      parentId: 2,
    },
    {
      name: 'Encendedores',
      id: 14,
      thumbImgUrl: 'null',
      parentId: null,
    },
    {
      name: 'Vasos',
      id: 112,
      thumbImgUrl: 'null',
      parentId: 11,
    },
    {
      name: 'Utensilios de limpieza',
      id: 64,
      thumbImgUrl: 'null',
      parentId: 4,
    },
    {
      name: 'Chocolate Mesa',
      id: 38,
      thumbImgUrl: 'null',
      parentId: 2,
    },
    {
      name: 'Ron',
      id: 19,
      thumbImgUrl: 'null',
      parentId: 1,
    },
    {
      name: 'Cuidado Íntimo',
      id: 52,
      thumbImgUrl: 'null',
      parentId: 3,
    },
    {
      name: 'Pasteles y Ponques',
      id: 77,
      thumbImgUrl: 'null',
      parentId: 5,
    },
    {
      name: 'Salsas',
      id: 42,
      thumbImgUrl: 'null',
      parentId: 2,
    },
    {
      name: 'Lavaloza y Desengrasante',
      id: 66,
      thumbImgUrl: 'null',
      parentId: 4,
    },
    {
      name: 'Granos',
      id: 34,
      thumbImgUrl: 'null',
      parentId: 2,
    },
    {
      name: 'Arroces',
      id: 31,
      thumbImgUrl: 'null',
      parentId: 2,
    },
    {
      name: 'Pastas',
      id: 32,
      thumbImgUrl: 'null',
      parentId: 2,
    },
    {
      name: 'Desodorantes y Talcos',
      id: 57,
      thumbImgUrl: 'null',
      parentId: 3,
    },
    {
      name: 'Afeitado y Depilación',
      id: 53,
      thumbImgUrl: 'null',
      parentId: 3,
    },
    {
      name: 'Cereales',
      id: 41,
      thumbImgUrl: 'null',
      parentId: 2,
    },
    {
      name: 'Jabones Barra Personal',
      id: 49,
      thumbImgUrl: 'null',
      parentId: 2,
    },
    {
      name: 'Alimentos Mascotas',
      id: 104,
      thumbImgUrl: 'null',
      parentId: 9,
    },
    {
      name: 'Harinas',
      id: 29,
      thumbImgUrl: 'null',
      parentId: 1,
    },
    {
      name: 'Condimentos',
      id: 40,
      thumbImgUrl: 'null',
      parentId: 2,
    },
    {
      name: 'Agua',
      id: 91,
      thumbImgUrl: 'null',
      parentId: 7,
    },
    {
      name: 'Aguardientes',
      id: 23,
      thumbImgUrl: 'null',
      parentId: 1,
    },
    {
      name: 'Otros Licores',
      id: 15,
      thumbImgUrl: 'null',
      parentId: 1,
    },
    {
      name: 'Galletas',
      id: 71,
      thumbImgUrl: 'null',
      parentId: 4,
    },
    {
      name: 'Detergentes en Polvo',
      id: 59,
      thumbImgUrl: 'null',
      parentId: 3,
    },
    {
      name: 'Gelatinas',
      id: 76,
      thumbImgUrl: 'null',
      parentId: 5,
    },
    {
      name: 'Cervezas',
      id: 16,
      thumbImgUrl: 'null',
      parentId: 1,
    },
    {
      name: 'Whiskys',
      id: 17,
      thumbImgUrl: 'null',
      parentId: 1,
    },
    {
      name: 'Palillos y Fósforos',
      id: 117,
      thumbImgUrl: 'null',
      parentId: 12,
    },
    {
      name: 'Enlatados',
      id: 44,
      thumbImgUrl: 'null',
      parentId: 2,
    },
    {
      name: 'Repostería',
      id: 80,
      thumbImgUrl: 'null',
      parentId: 5,
    },
    {
      name: 'Bolsas',
      id: 119,
      thumbImgUrl: 'null',
      parentId: 12,
    },
    {
      name: 'Maní y Frutos Secos',
      id: 79,
      thumbImgUrl: 'null',
      parentId: 5,
    },
    {
      name: 'Modificadores de Leche',
      id: 45,
      thumbImgUrl: 'null',
      parentId: 2,
    },
    {
      name: 'Azucar y Panela',
      id: 36,
      thumbImgUrl: 'null',
      parentId: 2,
    },
    {
      name: 'Aceites y Vinagres',
      id: 33,
      thumbImgUrl: 'null',
      parentId: 2,
    },
    {
      name: 'Bebidas Hidratantes',
      id: 94,
      thumbImgUrl: 'null',
      parentId: 7,
    },
    {
      name: 'Gaseosas',
      id: 89,
      thumbImgUrl: 'null',
      parentId: 6,
    },
    {
      name: 'Cigarrillos',
      id: 13,
      thumbImgUrl: 'null',
      parentId: null,
    },
    {
      name: 'Pasabocas',
      id: 78,
      thumbImgUrl: 'null',
      parentId: 5,
    },
    {
      name: 'Dulces',
      id: 74,
      thumbImgUrl: 'null',
      parentId: 5,
    },
    {
      name: 'Alivio del dolor y gripa',
      id: 99,
      thumbImgUrl: 'null',
      parentId: 8,
    },
    {
      name: 'Cafes',
      id: 30,
      thumbImgUrl: 'null',
      parentId: 1,
    },
    {
      name: null,
      id: null,
      thumbImgUrl: null,
      parentId: null,
    },
  ],
};
