export const PURCHASE_PRODUCTS_WALKTHROUGH_KEY =
  'PURCHASE_PRODUCTS_WALKTHROUGH';
export const SPEND_CATEGORY_WALKTHROUGH_KEY = 'SPEND_CATEGORY_WALKTHROUGH';
export const SALE_SHORTCUT_ACTIVATE_KEY = 'SALE_SHORTCUT_ACTIVATE_KEY';
export const SALE_SHORTCUT_FIRSTIME = 'SALE_SHORTCUT_FIRSTIME';
export const NEW_SALE_MODAL_COUNT_KEY = 'NEW_SALE_MODAL_COUNT';
export const USER_DATA_KEY = 'USER_DATA';
export const USER_CONFIG_KEY = 'USER_CONFIG';
export const STORE_KEY = 'STORE';
