name: Build and Deploy
on:
  push:
    branches:
      - staging
      - chores/ci

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Use Node.js 14
        uses: actions/setup-node@v1
        with:
          node-version: "14.17.6"

      - name: Setup npmrc
        run: echo -e "//npm.pkg.github.com/:_authToken=${{ secrets.PACKAGE_TOKEN }}\n@30sas:registry=https://npm.pkg.github.com/" > ~/.npmrc

      - uses: deptno/action-aws-ssm-to-dotenv@v1.3.2
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_STG }} # required
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_STG }} # required
          AWS_DEFAULT_REGION: us-west-2 # required
        with:
          ssm-path: /treinta/stg/treinta-suppliers-app/REACT_APP_PROJECT_ID
          format: dotenv
          output: .env

      - uses: deptno/action-aws-ssm-to-dotenv@v1.3.2
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_STG }} # required
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_STG }} # required
          AWS_DEFAULT_REGION: us-west-2 # required
        with:
          ssm-path: /treinta/stg/treinta-suppliers-app/REACT_APP_API_KEY_FIREBASE
          format: dotenv
          output: .env

      - name: Install dependencies
        run: yarn

      - name: Build
        run: yarn build
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Archive Production Artifact
        uses: actions/upload-artifact@master
        with:
          name: build
          path: build

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_STG }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_STG }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master

      - name: Download Artifact
        uses: actions/download-artifact@master
        with:
          name: build
          path: build

      - uses: deptno/action-aws-ssm-to-dotenv@v1.3.2
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_STG }} # required
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_STG }} # required
          AWS_DEFAULT_REGION: us-west-2 # required
        with:
          ssm-path: /treinta/stg/treinta-suppliers-app/DISTRIBUTION_ID
          format: shell
          output: .env

      - name: Deploy aws
        uses: reggionick/s3-deploy@v3
        with:
          folder: build
          bucket: treinta-suppliers-app-stg
          bucket-region: ${{ secrets.S3_BUCKET_REGION_OREGON }}
          dist-id: ${{ env.DISTRIBUTION_ID }}
          invalidation: /*
          delete-removed: true
          no-cache: true
          private: true
